import WhoWeAre from 'components/who';
import Head from 'next/head';
import Main from '../../components/main';
import Products from '../../components/products';
import History from '../../components/history';
import Footer from '../../components/footer/footer';
import Social from 'components/social';
import Contact from 'components/contact';
import Menu from 'components/menu/menu';

function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>Embutidos Gran Rey</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/images/favicon.png' />
			</Head>
			<main className='relative'>
				<Menu />
				<Main />
				<div id='product'>
					<Products />
				</div>
				<div id='whoweare'>
					<WhoWeAre />
				</div>
				<div id='history'>
					<History />
				</div>
				<div id='social'>
					<Social />
				</div>
				<div id='contact'>
					<Contact />
				</div>
				<Footer />
			</main>
		</>
	);
}

export default Home;
