import React from 'react';
import Head from 'next/head';

function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>Embutidos Gran Rey</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				Embutidos Gran Rey
				<div className='text-3xl text-red-dark p-2'>
					<h3>Testing Tailwincd Css</h3>
					<span>Subtitles Title Test</span>
				</div>
			</main>
		</>
	);
}

export default Home;
